name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        php_version: "8.1"
        version: 2

    - uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3306 # Optional, default value is 3306. The port of host
        container port: 3306 # Optional, default value is 3306. The port of container
        character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
        collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
        mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
        mysql database: 'testdb' # Optional, default value is "test". The specified database which will be create
        mysql root password: 'secret' # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql user: 'homestead' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: 'secret' # Required if "mysql user" exists. The password for the "mysql user"

    - name: config w
      run: ls -1 -d "$PWD/"* && bash run.sh

    - name: ls1
      run: ls -1 -d "$PWD/"*

    - name: df2 
      run: cd wordpress/wp-content/plugins/temp && php bones deploy updates HTTP_HOST=www.mysite.com && ls -1 -d "$PWD/"*

    - name: Updates Folder Zip Delete
      run: sudo rm -f updates/artlab-bulk-product-editor.zip
    - name: Run php bones
      run: sudo php bones
    - name: First Zip Delete
      run: ls -l ../ #rm artlab-bulk-product-editor.zip
    - name: Zip Rename
      run: mv artlab-bulk-product-editor2.zip updates/artlab-bulk-product-editor.zip
    - name: Remove existing update.json
      run: rm updates/update.json
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        fallback: 1.0.0
    - name: 'Get next minor version'
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previoustag.outputs.tag }}
    - name: Create copy of update.json using template
      run: cp updates/update-template.json updates/update.json
    - name: Replace version in update.json
      run: sed -i 's/_VERSION_/${{steps.semvers.outputs.patch}}/' updates/update.json
    - name: Replace version in plugin php file
      run: sed -i 's/${{ steps.previoustag.outputs.tag }}/${{steps.semvers.outputs.patch}}/' index.php
    - uses: EndBug/add-and-commit@v9
      with:
        tag: "${{steps.semvers.outputs.minor}}"