name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        php_version: "8.1"
        version: 2
    - name: Run composer
      run: sudo chown -R $USER ~/.composer && sudo composer install
    - name: Run composer
      run: sudo php bones deploy ../updates
    - name: Updates Folder Zip Delete
      run: sudo rm -f updates/artlab-bulk-product-editor.zip
    - name: Move Directory
      run: cd ../../
    - name: Zip Folder
      run: zip -r artlab-bulk-product-editor.zip ./updates -x ".git/*" ".github/*"
    - name: Initial Zip
      run: ls -l
    - name: Zip the Zip
      run: zip -r artlab-bulk-product-editor2.zip ./artlab-bulk-product-editor.zip
    - name: First Zip Delete
      run: rm artlab-bulk-product-editor.zip
    - name: Zip Rename
      run: mv artlab-bulk-product-editor2.zip updates/artlab-bulk-product-editor.zip
    - name: Remove existing update.json
      run: rm updates/update.json
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        fallback: 1.0.0
    - name: 'Get next minor version'
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previoustag.outputs.tag }}
    - name: Create copy of update.json using template
      run: cp updates/update-template.json updates/update.json
    - name: Replace version in update.json
      run: sed -i 's/_VERSION_/${{steps.semvers.outputs.patch}}/' updates/update.json
    - name: Replace version in plugin php file
      run: sed -i 's/${{ steps.previoustag.outputs.tag }}/${{steps.semvers.outputs.patch}}/' index.php
    - uses: EndBug/add-and-commit@v9
      with:
        tag: "${{steps.semvers.outputs.minor}}"