name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        php_version: "8.1"
        version: 2
    - name: Install composer
      run: sudo chown -R $USER ~/.composer && sudo composer install
    - name: Temp zip
      run: zip -r temp.zip .
    - name: Install wp-cli
      run: curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    - name: config wp-cli
      run: chmod +x wp-cli.phar
    - name: config wp-cli
      run: sudo mv wp-cli.phar /usr/local/bin/wp

    - name: create wordpress directory
      run: mkdir wordpress && cd wordpress
    - name: create wordpress
      run: wp core download
    - name: back to main
      run: cd .. && ls -l
    - name: move temp to wordpress
      run: mv temp.zip wp-content/plugins
    - name: unzip folder
      run: cd wp-content/plugins && unzip temp.zip -d temp && cd temp

    - name: ls
      run: ls -l

    - name: df 
      run: php bones deploy updatesfff
      
    - name: ls
      run: ls -1 -d "$PWD/"*

    - name: Updates Folder Zip Delete
      run: sudo rm -f updates/artlab-bulk-product-editor.zip
    - name: Run php bones
      run: sudo php bones
    - name: First Zip Delete
      run: ls -l ../ #rm artlab-bulk-product-editor.zip
    - name: Zip Rename
      run: mv artlab-bulk-product-editor2.zip updates/artlab-bulk-product-editor.zip
    - name: Remove existing update.json
      run: rm updates/update.json
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        fallback: 1.0.0
    - name: 'Get next minor version'
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previoustag.outputs.tag }}
    - name: Create copy of update.json using template
      run: cp updates/update-template.json updates/update.json
    - name: Replace version in update.json
      run: sed -i 's/_VERSION_/${{steps.semvers.outputs.patch}}/' updates/update.json
    - name: Replace version in plugin php file
      run: sed -i 's/${{ steps.previoustag.outputs.tag }}/${{steps.semvers.outputs.patch}}/' index.php
    - uses: EndBug/add-and-commit@v9
      with:
        tag: "${{steps.semvers.outputs.minor}}"